    PrimeFaces.locales['tr'] = {  
        closeText: 'kapat',  
        prevText: 'geri',  
        nextText: 'ileri',  
        currentText: 'bugün',  
        monthNames: ['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran',  
        'Temmuz','Aƒüustos','Eylül','Ekim','Kasım','Aralık'],  
        monthNamesShort: ['Oca','≈ûub','Mar','Nis','May','Haz',  
        'Tem','Ağu','Eyl','Eki','Kas','Ara'],  
        dayNames: ['Pazar','Pazartesi','Salƒ±','√áar≈üamba','Perşembe','Cuma','Cumartesi'],  
        dayNamesShort: ['Pz','Pt','Sa','√áa','Pe','Cu','Ct'],  
        dayNamesMin: ['Pz','Pt','Sa','√áa','Pe','Cu','Ct'],  
        weekHeader: 'Hf',  
        firstDay: 1,  
        isRTL: false,  
        showMonthAfterYear: false,  
        yearSuffix: '',  
        month: 'Ay',  
        week: 'Hafta',  
        day: 'Gün',  
        allDayText : 'Tüm Gün'  
    };
    
    PrimeFaces.locales['hu']= {
            closeText: 'Bezárás',
            prevText: 'Előző',
            nextText: 'Következő',
            monthNames: ['Január', 'Február', 'Március', 'Április', 'Május', 'Június', 'Július', 'Augusztus', 'Szeptember', 'Október', 'November', 'December' ],
            monthNamesShort: ['Jan', 'Febr', 'Márc', 'Ápr', 'Máj', 'Jún', 'Júl', 'Aug', 'Szept', 'Okt', 'Nov', 'Dec'],
            dayNames: ['Vasárnap', 'Hétfő', 'Kedd', 'Szerda', 'Csütörtök', 'Péntek', 'Szombat'],
            dayNamesShort: ['Vas', 'H', 'K', 'Sze', 'Csüt', 'P', 'Szo'],
            dayNamesMin: ['V', 'H', 'K', 'Sze ', 'Cs', 'P ', 'Szo'],
            weekHeader: 'Hét',
            firstDay: 1,
            isRTL: false,
            showMonthAfterYear: true,
            yearSuffix:'.',
            timeOnlyTitle: 'Csak óra',
            timeText: 'Időpont',
            hourText: 'Óra',
            minuteText: 'Perc',
            secondText: 'Másodperc',
            currentText: 'Ma',
            ampm: false,
            month: 'Hónap',
            week: 'Hét',
            day: 'Nap',
            allDayText: 'Egész nap'
        };
